spring:
  profiles:
    active: local
    group:
      local:
        - db-dev
#        - security-dev
        - global-dev
      dev:
        - db-dev
#        - security-dev
        - global-dev
      prod:
        - db-dev
#        - security-prod
        - global-prod
    include:
      - db
      - global
      - security