server:
  port: 8080

--- # local & dev
spring:
  config:
    activate:
      on-profile: global-dev
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.type: off
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari: INFO
    com: debug

--- # prod
spring:
  config:
    activate:
      on-profile: global-prod

logging:
  level:
    com: info